---
title: "Academic and Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Education

**[Columbia University Mailman School of Public Health](https://www.publichealth.columbia.edu)
*M.S. in Bio-statistics, 2021-2023

**[University of California, Santa Barbara](https://www.ucsb.edu)
*B.A. in Actuarial Science, 2016-2019

## Professional Experience

*Capital Securities Co., Ltd.∣Beijing, China                                 
Intern, Innovative Business Department, Dec 2018 – Dec 2020

•	Implemented alpha arbitrage strategy in HFT alpha hedge fund, analyzed and evaluated the performance of the strategy

•	Designed investment strategies based on Capital Asset Pricing Model, Jensen's alpha, derived Alpha combined yield formula

•	Analyzed the risk, volatility, and return of the investment strategies under various market conditions

*Southwest Securities Company, Ltd∣Beijing, China                               
Assistant, Investment Banking Department, 06/2019 – 08/2019

•	Collected financial reports and conducted due diligence of target companies using the Wind Economic Database to help the team evaluate the decision of acquisition, issuance of bonds, or whether a company should go public

•	Conducted statistical analysis and wrote up reports of the findings

•	Forecasted stock price and selected stocks with multi-factor selection model and residual income valuation model

•	Examined prices of futures contracts through a factor regression model that has the market fundamental factors as regressors


Go back to the [home](index.html)
